odom_frame: odom
base_link_frame: base_link
world_frame: odom

two_d_mode: true

frequency: 50

odom0: khan_velocity_controller/odom
odom0_config: [true, true, true,
               false, false, true,
               false, false, false,
               false, false, false,
               false, false, false]
odom0_differential: true


